### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nielsgroen** [schipiga/pandas-tfrecords#2]
I'd like to extract some snippets of code from this repo.
But now I'm wondering under what license this code falls.

Could you provide a license accompanying the code?

You could, as an example, do it like google did for tfx, and include a ['LICENSE' file](https://github.com/tensorflow/tfx/blob/master/LICENSE).

Many thanks!

**Comment by schipiga** [comment]
Hi!
Feel free to send pull-request with a license, which you are interesting.
